package com.confluence.docassistant.agent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

/**
 * PageResolver — dynamically finds which Confluence page best answers a question.
 *
 * Uses L1 summary chunks stored in PgVector to match questions to pages.
 * Zero hardcoding — works for any page in any Confluence space.
 *
 * Flow:
 * 1. Embed the user question
 * 2. Search only L1 chunks (page summaries) by vector similarity
 * 3. Return the title of the best matching page
 *
 * Why L1 only:
 * L1 chunks contain the page summary + all synonyms + hypothetical questions
 * generated by SemanticEnricher. They are specifically designed for page-level matching.
 * Searching L1 only means we get page-level intent, not row-level noise.
 */
@Component
public class PageResolver {

    private static final Logger log = LoggerFactory.getLogger(PageResolver.class);
    private static final double MIN_CONFIDENCE = 0.45;

    private final JdbcTemplate    jdbc;
    private final EmbeddingModel  embeddingModel;

    public PageResolver(JdbcTemplate jdbc, EmbeddingModel embeddingModel) {
        this.jdbc           = jdbc;
        this.embeddingModel = embeddingModel;
    }

    /**
     * Finds the most relevant page for a question by searching L1 summaries.
     *
     * @param question user question
     * @return page title if confident match found, empty otherwise
     */
    public Optional<String> findBestPage(String question) {
        try {
            float[] embedding = embeddingModel.embed(question);
            String  vectorStr = toVectorString(embedding);

            List<PageMatch> matches = jdbc.query("""
                    SELECT
                        metadata->>'title'                              AS title,
                        1 - (embedding <=> '%s'::vector)               AS score
                    FROM vector_store
                    WHERE metadata->>'layer' = 'L1'
                    ORDER BY embedding <=> '%s'::vector
                    LIMIT 3
                    """.formatted(vectorStr, vectorStr),
                    (rs, row) -> new PageMatch(
                            rs.getString("title"),
                            rs.getDouble("score")
                    )
            );

            if (matches.isEmpty()) return Optional.empty();

            PageMatch best = matches.get(0);
            log.debug("PageResolver: best match '{}' score={}",
                    best.title(), String.format("%.3f", best.score()));

            // Only return if confidence is high enough
            if (best.score() < MIN_CONFIDENCE) {
                log.debug("PageResolver: score too low ({}) — not confident", String.format("%.3f", best.score()));
                return Optional.empty();
            }

            // If top result is significantly better than second — high confidence
            if (matches.size() > 1) {
                double gap = best.score() - matches.get(1).score();
                if (gap < 0.03 && best.score() < 0.65) {
                    // Too close — ambiguous question, don't force a page
                    log.debug("PageResolver: ambiguous ({} vs {}) — skipping",
                            String.format("%.3f", best.score()), String.format("%.3f", matches.get(1).score()));
                    return Optional.empty();
                }
            }

            log.info("PageResolver: resolved '{}' → '{}'", question, best.title());
            return Optional.of(best.title());

        } catch (Exception e) {
            log.warn("PageResolver failed: {}", e.getMessage());
            return Optional.empty();
        }
    }

    private String toVectorString(float[] embedding) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < embedding.length; i++) {
            if (i > 0) sb.append(",");
            sb.append(embedding[i]);
        }
        return sb.append("]").toString();
    }

    public record PageMatch(String title, double score) {}
}